#!/usr/bin/env bats

setup() {
  : "${FIGURECTL_ARTIFACT:?FIGURECTL_ARTIFACT must identify the artifact under test}"
}

@test "artifact is executable" {
  [ -x "${FIGURECTL_ARTIFACT}" ]
}

@test "artifact has a .sha256 checksum companion" {
  [ -f "${FIGURECTL_ARTIFACT}.sha256" ]
  [ ! -e "${FIGURECTL_ARTIFACT}.256" ]
}

@test "checksum companion verifies the artifact bytes" {
  local artifact_dir artifact_name expected actual
  artifact_dir="$(dirname "${FIGURECTL_ARTIFACT}")"
  artifact_name="$(basename "${FIGURECTL_ARTIFACT}")"
  expected="$(awk '{print $1}' "${FIGURECTL_ARTIFACT}.sha256")"

  if command -v sha256sum >/dev/null 2>&1; then
    actual="$(sha256sum "${FIGURECTL_ARTIFACT}" | awk '{print $1}')"
  elif command -v shasum >/dev/null 2>&1; then
    actual="$(shasum -a 256 "${FIGURECTL_ARTIFACT}" | awk '{print $1}')"
  else
    skip "No SHA-256 verification command is available"
  fi

  [ "${expected}" = "${actual}" ]
  grep -Fq "  ${artifact_name}" "${FIGURECTL_ARTIFACT}.sha256"
  [ -d "${artifact_dir}" ]
}

@test "artifact passes Bash syntax validation" {
  run bash -n "${FIGURECTL_ARTIFACT}"
  [ "${status}" -eq 0 ]
}

@test "development artifact retains embedded AWK documentation only in dev flavor" {
  local artifact_name
  artifact_name="$(basename "${FIGURECTL_ARTIFACT}")"

  if [[ "${artifact_name}" == *.dev.bash ]]; then
    grep -Fq '## @file lib/awk/common.awk' "${FIGURECTL_ARTIFACT}"
    grep -Fq '# Generated by make build. Do not edit directly.' "${FIGURECTL_ARTIFACT}"
  else
    ! grep -Fq '## @file lib/awk/common.awk' "${FIGURECTL_ARTIFACT}"
    ! grep -Fq '# Generated by make build. Do not edit directly.' "${FIGURECTL_ARTIFACT}"
  fi
}

@test "artifact contains figurectl provenance variables" {
  grep -Fq 'FIGURECTL_VERSION=' "${FIGURECTL_ARTIFACT}"
  grep -Fq 'FIGURECTL_BUILD_DATE=' "${FIGURECTL_ARTIFACT}"
  grep -Fq 'FIGURECTL_BUILD_COMMIT=' "${FIGURECTL_ARTIFACT}"
}
